# Generated by Django 3.2.12 on 2024-08-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching_space', '0007_auto_20240821_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='事项名')),
                ('initiator', models.CharField(max_length=255, verbose_name='发起人')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('agreed', '已同意'), ('rejected', '已拒绝')],
                                            default='pending', max_length=50, verbose_name='状态')),
                ('created_datetime', models.DateField(auto_now_add=True, verbose_name='发起时间')),
                ('review', models.TextField(default='', verbose_name='课后复盘')),
                ('training_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='instructor_event',
                                                        to='teaching_space.trainingclass',
                                                        verbose_name='培训班')),
            ],
        ),
    ]
