# Generated by Django 3.2.12 on 2024-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lectures', '0002_advertisement_instructorenrolment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorevent',
            name='status',
            field=models.CharField(
                choices=[('pending', '待处理'), ('agreed', '已同意'), ('rejected', '已拒绝'), ('removed', '已被移除')],
                default='pending', max_length=50, verbose_name='状态'),
        ),
    ]
