# Generated by Django 3.2.12 on 2024-09-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lectures', '0006_auto_20240903_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorevent',
            name='event_type',
            field=models.CharField(
                choices=[('invite_to_class', '邀请上课'), ('post_class_review', '课后复盘')],
                default='invite_to_class',
                max_length=32,
                verbose_name='事件类型'),
        ),
    ]
