# Generated by Django 3.2.12 on 2024-10-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_lectures', '0009_alter_instructorevent_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorenrolment',
            options={'verbose_name': '讲师报名表', 'verbose_name_plural': '讲师报名表'},
        ),
        migrations.AlterModelOptions(
            name='instructorevent',
            options={'verbose_name': '讲师事项', 'verbose_name_plural': '讲师事项'},
        ),
    ]
