# Generated by Django 3.2.12 on 2024-11-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lectures', '0010_auto_20241009_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_revoked',
            field=models.BooleanField(default=False, verbose_name='是否已撤销'),
        ),
        migrations.AlterField(
            model_name='instructorenrolment',
            name='status',
            field=models.CharField(
                choices=[('accepted', '已聘用'), ('pending', '待聘用'), ('not_enrolled', '未报名'),
                         ('rejected', '未聘用'), ('timeout', '已过期'), ('revoke', '已撤销')],
                default='pending',
                max_length=16
            ),
        ),
    ]
