# Generated by Django 3.2.12 on 2025-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lectures', '0012_alter_instructorevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorenrolment',
            name='status',
            field=models.CharField(
                choices=[('accepted', '已聘用'),
                         ('pending', '待聘用'),
                         ('not_enrolled', '未报名'),
                         ('rejected', '未聘用'),
                         ('timeout', '已过期'),
                         ('revoke', '已撤销')],
                default='pending',
                max_length=16,
                verbose_name='状态'),
        ),
    ]
