# Generated by Django 3.2.4 on 2024-07-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0002_auto_20240725_1535"),
        ("teaching_space", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingclass",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_classes",
                to="platform_management.instructor",
                verbose_name="讲师",
            ),
        ),
    ]
