# Generated by Django 3.2.4 on 2024-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teaching_space", "0002_alter_trainingclass_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingclass",
            name="course_name",
            field=models.CharField(max_length=64, verbose_name="课程"),
        ),
    ]
