# Generated by Django 3.2.4 on 2024-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teaching_space", "0004_trainingclass_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingclass",
            name="assessment_method",
            field=models.CharField(
                choices=[
                    ("closed_book_exam", "闭卷考试"),
                    ("computer_exam", "闭卷机考"),
                    ("practical", "实操"),
                    ("defense", "答辩"),
                ],
                max_length=16,
                verbose_name="考核方式",
            ),
        ),
        migrations.AlterField(
            model_name="trainingclass",
            name="class_mode",
            field=models.CharField(
                choices=[("online", "线上课"), ("offline", "线下课")],
                max_length=16,
                verbose_name="上课模式",
            ),
        ),
        migrations.AlterField(
            model_name="trainingclass",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "筹备中"),
                    ("in_progress", "开课中"),
                    ("completed", "已结课"),
                ],
                max_length=16,
                verbose_name="状态",
            ),
        ),
    ]
