# Generated by Django 3.2.12 on 2024-08-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0025_rename_type_event_event_type'),
        ('teaching_space', '0005_auto_20240809_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='trainingclass',
            name='target_client_company_name',
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='training_classes', to='platform_management.coursetemplate',
                                    verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='target_client_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='training_classes', to='platform_management.clientcompany',
                                    verbose_name='客户公司'),
        ),
        migrations.AlterField(
            model_name='trainingclass',
            name='certification',
            field=models.CharField(choices=[('miit_talent_center', '工信部人才中心'), ('exam_center', '教考中心')],
                                   max_length=32, verbose_name='认证证书'),
        ),
    ]
