# Generated by Django 3.2.12 on 2024-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0006_auto_20240821_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='certification',
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='certification_body',
            field=models.JSONField(choices=[('miit_talent_center', '工信部人才中心'), ('exam_center', '教考中心')],
                                   default=list, verbose_name='认证机构'),
        ),
    ]
