# Generated by Django 3.2.12 on 2024-09-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0008_trainingclass_publish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='student_count',
        ),
    ]
