# Generated by Django 3.2.12 on 2024-09-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0009_remove_trainingclass_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='creator',
            field=models.CharField(default='', max_length=32, verbose_name='创建人'),
        ),
    ]
