# Generated by Django 3.2.12 on 2024-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0010_trainingclass_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='certification_body',
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='certification',
            field=models.CharField(default='', max_length=32, verbose_name='认证证书'),
        ),
    ]
