# Generated by Django 3.2.12 on 2024-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0011_auto_20240918_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='course_status',
            field=models.CharField(choices=[('preparation', '准备期'), ('in_progress', '授课'),
                                            ('suspended', '暂停'), ('terminated', '停课')],
                                   default='preparation', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='trainingclass',
            name='class_mode',
            field=models.CharField(choices=[('online', '线上课'), ('offline', '线下课')],
                                   default='online', max_length=16, verbose_name='上课模式'),
        ),
        migrations.AlterField(
            model_name='trainingclass',
            name='status',
            field=models.CharField(choices=[('preparing', '筹备中'), ('in_progress', '开课中'),
                                            ('completed', '已结课')], default='preparing',
                                   max_length=16, verbose_name='状态'),
        ),
    ]
