# Generated by Django 3.2.12 on 2024-10-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0013_trainingclass_questionnaire_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingclass',
            options={'verbose_name': '培训班', 'verbose_name_plural': '培训班'},
        ),
    ]
