# Generated by Django 3.2.12 on 2024-10-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0034_auto_20241009_1623'),
        ('teaching_space', '0014_alter_trainingclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='client_students',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='training_classes',
                to='platform_management.ClientStudent', verbose_name='客户学员'),
        ),
    ]
