# Generated by Django 3.2.12 on 2024-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0015_trainingclass_client_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclass',
            name='review',
            field=models.TextField(
                default='<h2>进展好的方面</h2>\n\n'
                        '<h2>进展的不太顺利的方面</h2>\n\n'
                        '<h2>学员总体情况 （基础、接受度、与工作相关度等）</h2>\n\n'
                        '<h2>课堂氛围（提问和讨论等）</h2>\n\n'
                        '<h2>关于教材（是否识别到需要优化和勘误的地方）</h2>',
                verbose_name='课后复盘'),
        ),
    ]
