# Generated by Django 3.2.12 on 2024-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0035_init_administrator'),
        ('teaching_space', '0016_alter_trainingclass_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclass',
            name='client_students',
            field=models.ManyToManyField(
                blank=True,
                related_name='training_classes',
                to='platform_management.ClientStudent',
                verbose_name='客户学员'),
        ),
    ]
