# Generated by Django 3.2.12 on 2024-11-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0017_alter_trainingclass_client_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclass',
            name='status',
            field=models.CharField(
                choices=[('preparing', '筹备中'), ('in_progress', '开课中'),
                         ('completed', '已结课'), ('cancelled', '已取消')],
                default='preparing',
                max_length=16,
                verbose_name='状态'
            ),
        ),
    ]
