# Generated by Django 3.2.12 on 2024-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0018_alter_trainingclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='passing_score',
            field=models.IntegerField(default=0, verbose_name='及格总分数线'),
        ),
    ]
