# Generated by Django 3.2.12 on 2024-12-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0019_trainingclass_passing_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingclass',
            options={'ordering': ['-id'], 'verbose_name': '培训班', 'verbose_name_plural': '培训班'},
        ),
    ]
