# Generated by Django 3.2.12 on 2024-12-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0020_alter_trainingclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布成绩'),
        ),
    ]
