version: '3'

services:
  db:
    image: mysql:8.3
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training-center-test

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  web:
    build: .
    image: training-center_web:latest
    command: sh -c "python manage.py migrate && /usr/bin/supervisord"
    volumes:
      - ./training-center-api:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db
    environment:
      # mysql配置
      DATABASE_HOST: db
      DATABASE_NAME: training-center-test
      DATABASE_USER: root
      DATABASE_PASSWORD: root

      # redis配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_INDEX: 1

      # 环境
      BK_ENV: production

      # cos配置
      COS_SECRET_ID:
      COS_SECRET_KEY:
      COS_REGION:
      COS_BUCKET:

      # 前端环境变量
      BK_API_HOST: http://cert.sre-elite.com

      # 是否启用SMS(不启用注释掉该配置)
      # ENABLE_SMS: "true"
      SMS_USERNAME:
      SMS_PASSWORD:

  db_test:
    image: mysql:8.3
    volumes:
      - db_data_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training-center-test2

  redis_test:
    image: redis:latest
    volumes:
      - redis_data_test:/data

  web_test:
    build: .
    image: training-center_web:latest
    command: sh -c "python manage.py migrate && /usr/bin/supervisord"
    volumes:
      - ./training-center-api:/usr/src/app
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    links:
      - db
    environment:
      # mysql配置
      DATABASE_HOST: db
      DATABASE_NAME: training-center-test2
      DATABASE_USER: root
      DATABASE_PASSWORD: root

      # redis配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_INDEX: 1

      # 环境
      BK_ENV: production

      # 是否启用sms
      ENABLE_SMS: "true"
      SMS_USERNAME:
      SMS_PASSWORD:

      # cos配置
      COS_SECRET_ID:
      COS_SECRET_KEY:
      COS_REGION:
      COS_BUCKET:

      # 前端环境变量
      BK_API_HOST: http://cert.sre-elite.com

volumes:
  db_data:
  redis_data:
  db_data_test:
  redis_data_test:
