# Generated by Django 3.2.4 on 2024-07-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0002_auto_20240725_1535"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientstudent",
            old_name="affiliated_client_company",
            new_name="affiliated_client_company_name",
        ),
    ]
