# Generated by Django 3.2.4 on 2024-07-22 08:07

from django.db import migrations, models
import django.contrib.auth.models
import django.utils.timezone


def add_initial_instructor_data(apps, schema_editor):
    # 获取模型
    manage_company = apps.get_model("platform_management", "ManageCompany")

    # 创建初始数据
    manage_company.objects.create(name="鸿雪公司", type="默认公司")


class Migration(migrations.Migration):
    dependencies = [
        ("platform_management", "0002_administrator_instructor_managecompany"),
    ]

    operations = [
        migrations.RunPython(add_initial_instructor_data),
    ]
