# Generated by Django 3.2.4 on 2024-07-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_management",
            "0003_rename_affiliated_client_company_clientstudent_affiliated_client_company_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetemplate",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="课程名称"),
        ),
    ]
