# Generated by Django 3.2.4 on 2024-07-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0004_alter_coursetemplate_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientcompany",
            old_name="affiliated_manage_company",
            new_name="affiliated_manage_company_name",
        ),
    ]
