# Generated by Django 3.2.4 on 2024-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_management",
            "0006_rename_manage_company_administrator_affiliated_manage_company_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientApprovalSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="标题")),
                (
                    "affiliated_manage_company_name",
                    models.CharField(max_length=32, verbose_name="管理公司"),
                ),
                (
                    "affiliated_client_company_name",
                    models.CharField(max_length=32, verbose_name="客户公司"),
                ),
                ("submitter", models.CharField(max_length=32, verbose_name="提单人")),
                ("submission_datetime", models.DateTimeField(verbose_name="提单时间")),
                (
                    "status",
                    models.CharField(default="待处理", max_length=32, verbose_name="状态"),
                ),
                (
                    "submission_info",
                    models.JSONField(default=dict, verbose_name="提交信息"),
                ),
            ],
        ),
    ]
