# Generated by Django 3.2.4 on 2024-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0008_instructor_id_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientapprovalslip",
            name="status",
            field=models.CharField(
                choices=[("待处理", "待处理"), ("同意", "同意"), ("驳回", "驳回")],
                default="待处理",
                max_length=32,
                verbose_name="状态",
            ),
        ),
    ]
