# Generated by Django 3.2.4 on 2024-08-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0009_alter_clientapprovalslip_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientstudent",
            old_name="name",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="instructor",
            old_name="name",
            new_name="username",
        ),
    ]
