# Generated by Django 3.2.4 on 2024-08-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0010_auto_20240801_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="username",
            field=models.CharField(db_index=True, max_length=64, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="clientstudent",
            name="username",
            field=models.CharField(max_length=64, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="course_content",
            field=models.TextField(verbose_name="课程内容"),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="username",
            field=models.CharField(db_index=True, max_length=64, verbose_name="姓名"),
        ),
    ]
