# Generated by Django 3.2.4 on 2024-08-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0011_auto_20240802_0934"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientstudent",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后登录时间"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后登录时间"),
        ),
    ]
