# Generated by Django 3.2.4 on 2024-08-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0012_auto_20240804_1220"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientstudent",
            name="password",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="password",
        ),
    ]
