# Generated by Django 3.2.4 on 2024-08-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0012_auto_20240802_1105"),
        ("platform_management", "0013_auto_20240804_1221"),
    ]

    operations = []
