# Generated by Django 3.2.4 on 2024-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0016_alter_coursetemplate_exam_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=16, unique=True, verbose_name="手机号码"
            ),
        ),
        migrations.AlterField(
            model_name="clientstudent",
            name="phone",
            field=models.CharField(max_length=16, unique=True, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="exam_type",
            field=models.JSONField(
                choices=[
                    ("multiple_choice", "多选题"),
                    ("single_choice", "单选题"),
                    ("subjective", "主观题"),
                ],
                default=list,
                verbose_name="考试题型",
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="phone",
            field=models.CharField(max_length=16, unique=True, verbose_name="电话"),
        ),
    ]
