# Generated by Django 3.2.4 on 2024-08-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_management",
            "0019_rename_affiliated_manage_company_name_administrator_affiliated_manage_company",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursetemplate",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="administrator",
            name="affiliated_manage_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administrators",
                to="platform_management.managecompany",
                verbose_name="管理公司",
            ),
        ),
        migrations.AlterField(
            model_name="clientstudent",
            name="education",
            field=models.CharField(
                choices=[
                    ("highschool", "高中"),
                    ("associate", "专科"),
                    ("bachelor", "本科"),
                    ("master", "硕士研究生"),
                    ("doctorate", "博士生"),
                ],
                max_length=32,
                verbose_name="学历",
            ),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="exam_duration",
            field=models.IntegerField(
                choices=[("45", "45分钟"), ("90", "90分钟"), ("120", "120分钟")],
                verbose_name="考试时长",
            ),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="learning_benefits",
            field=models.TextField(default="", verbose_name="学习收益"),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="learning_objectives",
            field=models.TextField(default="", verbose_name="学习目标"),
        ),
        migrations.AlterField(
            model_name="coursetemplate",
            name="target_students",
            field=models.TextField(default="", verbose_name="目标学员"),
        ),
    ]
