# Generated by Django 3.2.4 on 2024-08-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teaching_space", "0005_auto_20240809_1656"),
        ("platform_management", "0020_auto_20240809_1656"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("class_schedule", "培训班排课"),
                            ("one_time_unavailability", "登记一次性不可用时间规则"),
                            ("recurring_unavailability", "登记周期性不可用时间规则"),
                            ("cancel_unavailability", "取消单日不可用时间"),
                        ],
                        max_length=50,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "freq_type",
                    models.CharField(
                        choices=[("weekly", "每周"), ("monthly", "每月")], max_length=16
                    ),
                ),
                ("freq_interval", models.JSONField(default=list)),
                ("start_date", models.DateField(verbose_name="开始时间")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "training_class",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teaching_space.trainingclass",
                        verbose_name="培训班",
                    ),
                ),
            ],
            options={
                "verbose_name": "日程事件",
                "verbose_name_plural": "日程事件",
            },
        ),
    ]
