# Generated by Django 3.2.4 on 2024-08-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0021_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="freq_type",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "每周"), ("monthly", "每月")],
                max_length=16,
                null=True,
            ),
        ),
    ]
