# Generated by Django 3.2.4 on 2024-08-16 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0022_alter_event_freq_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="created_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientstudent",
            name="created_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
    ]
