# Generated by Django 3.2.4 on 2024-08-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("platform_management", "0023_auto_20240816_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="platform_management.instructor",
            ),
        ),
    ]
