# Generated by Django 3.2.12 on 2024-08-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0007_auto_20240821_1549'),
        ('platform_management', '0025_rename_type_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='events', to='platform_management.instructor', verbose_name='讲师'),
        ),
        migrations.AlterField(
            model_name='event',
            name='training_class',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE, related_name='events',
                                       to='teaching_space.trainingclass', verbose_name='培训班'),
        ),
    ]
