# Generated by Django 3.2.12 on 2024-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0026_auto_20240821_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='teaching_count',
            field=models.IntegerField(default=0, verbose_name='授课次数'),
        ),
    ]
