# Generated by Django 3.2.12 on 2024-08-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0027_coursetemplate_teaching_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetemplate',
            name='teaching_count',
        ),
    ]
