# Generated by Django 3.2.12 on 2024-09-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_space', '0009_remove_trainingclass_student_count'),
        ('platform_management', '0028_remove_coursetemplate_teaching_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='training_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='event', to='teaching_space.trainingclass', verbose_name='培训班'),
        ),
    ]
