# Generated by Django 3.2.12 on 2024-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0030_auto_20240926_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetemplate',
            name='exam_duration',
            field=models.IntegerField(
                blank=True, choices=[('45', '45分钟'), ('90', '90分钟'), ('120', '120分钟')],
                null=True, verbose_name='考试时长'),
        ),
    ]
