# Generated by Django 3.2.12 on 2024-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0032_alter_coursetemplate_exam_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetemplate',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='考题数量'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='passing_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='过线分数'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='require_authorized_training',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否要求授权培训'),
        ),
    ]
