# Generated by Django 3.2.12 on 2024-10-09 08:23
from django.conf import settings
from django.db import migrations
from django.utils import timezone


def create_initial_records(apps, schema_editor):
    ManageCompany = apps.get_model('platform_management', 'ManageCompany')
    Administrator = apps.get_model('platform_management', 'Administrator')

    # 初始化一个admin用户
    if Administrator.objects.count() == 0:
        manage_company_instance = ManageCompany.objects.create(
            name='鸿雪公司',
            email='hongxue@qq.com',
            type='default'
        )

        now = timezone.now()
        Administrator.objects.create(
            id=1,
            password='123456',
            last_login=now,
            is_superuser=True,
            first_name='admin',
            last_name='admin',
            email='admin@qq.com',
            is_staff=True,
            is_active=True,
            date_joined=now,
            username='admin',
            phone=settings.ADMIN_PHONE,
            affiliated_manage_company=manage_company_instance,  # 使用 ManageCompany 实例
            role='super_manager'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0034_auto_20241009_1623'),
    ]

    operations = [
        migrations.RunPython(create_initial_records),
    ]
