# Generated by Django 3.2.12 on 2024-10-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0035_init_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstudent',
            name='id_photo',
            field=models.JSONField(verbose_name='证件照'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id_photo',
            field=models.JSONField(verbose_name='证件照'),
        ),
    ]
