# Generated by Django 3.2.12 on 2024-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0036_auto_20241030_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(db_index=True, max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='clientapprovalslip',
            name='affiliated_client_company_name',
            field=models.CharField(max_length=128, verbose_name='客户公司'),
        ),
        migrations.AlterField(
            model_name='clientapprovalslip',
            name='affiliated_manage_company_name',
            field=models.CharField(max_length=128, verbose_name='管理公司'),
        ),
        migrations.AlterField(
            model_name='clientapprovalslip',
            name='name',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='clientapprovalslip',
            name='submitter',
            field=models.CharField(max_length=128, verbose_name='提单人'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='affiliated_manage_company_name',
            field=models.CharField(max_length=128, verbose_name='管理公司'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='bank_account',
            field=models.CharField(max_length=64, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='bank_name',
            field=models.CharField(max_length=128, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='certificate_address',
            field=models.CharField(max_length=256, verbose_name='证书收件地址'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='contact_email',
            field=models.EmailField(max_length=256, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='contact_person',
            field=models.CharField(max_length=128, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='invoice_company_name',
            field=models.CharField(max_length=128, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='客户公司名称'),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='recipient_name',
            field=models.CharField(max_length=128, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='clientstudent',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='clientstudent',
            name='username',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[('class_schedule', '培训班排课'),
                         ('one_time_unavailability', '登记一次性不可用时间规则'),
                         ('recurring_unavailability', '登记周期性不可用时间规则'),
                         ('cancel_unavailability', '取消单日不可用时间')],
                max_length=64,
                verbose_name='事件类型'
            ),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(max_length=64, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='company',
            field=models.CharField(max_length=256, verbose_name='所在公司'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.CharField(db_index=True, max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='managecompany',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='managecompany',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='名称'),
        ),
    ]
