# Generated by Django 3.2.12 on 2024-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0038_auto_20241101_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstudent',
            name='department',
            field=models.CharField(blank=True, max_length=128, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='clientstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=256, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='clientstudent',
            name='id_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='clientstudent',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='职位'),
        ),
    ]
